backend:
  name: github
  repo: Everpoint/everpoint-site
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "about"
    label: "Сми о нас"
    widget: "string"
    folder: "src/data/about"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
      - {label: "Заголовок", name: "title", widget: "string", pattern: ["^.{1,100}$", "Не больше 100 символов"]}
      - {label: "Дата публикации", name: "date", widget: "date"}
      - {label: "Краткое описание", name: "description", widget: "text", pattern: ["^.{1,250}$", "Не больше 250 символов"] }
      - {label: "Ссылка", name: "link", widget: "string"}
      - {label: "Логотип", name: "logo", widget: image}
      - {label: "Отображать на главной", name: "isVisible", widget: "boolean", default: false}
  - name: "pages"
    label: "Страницы"
    files:
      - file: "src/data/pages/about-page.md"
        label: "Новостная страница, родительский маршрут /about"
        name: "about-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "page Id", name: "id", widget: "hidden"}
          - {label: "Новостной блок /about", name: "title", widget: "string"}
      - file: "src/data/pages/contact-page.md"
        label: "Страница контактов, родительский маршрут /contacts"
        name: "contact-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "page Id", name: "id", widget: "hidden"}
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Адрес", name: "address", widget: "string"}
          - {label: "Телефон", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
  - name: "vacancy"
    label: "Вакансии"
    widget: "string"
    folder: "src/data/vacancy"
    identifier_field: "name"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "vacancy"}
      - {label: "Отображать на главной", name: "isVisible", widget: "boolean", default: true}
      - {label: "Название вакансии", name: "name", widget: "string"}
      - {label: "Аватар", name: "avatar", widget: image}
      - {label: "Формат работы", name: "workFormat", widget: "string"}
      - {label: "Занятость", name: "employment", widget: "string"}
      - {label: "Оклад", name: "salary", widget: "string", required: false, default: ""}
      - label: "Контакты"
        name: "contacts"
        widget: "object"
        fields:
          - {label: "ФИО", name: "fullName", widget: "string"}
          - {label: "Telegram", name: "telegram", widget: "string", required: false, default: ""}
          - {label: "Email", name: "email", widget: "string"}
      - {label: "Ключевые навыки", name: "skills", widget: "list", required: false, default: [null]}
      - label: 'Блок "Что мы ждем от вас"'
        name: "expectations"
        widget: "object"
        fields:
          - {label: "Название блока", name: "expectationsTitle", widget: "string", default: "Что мы ждем от вас"}
          - {label: 'Перечень требований', name: 'requirementsList', widget: 'markdown'}
      - label: 'Блок с вложением"'
        name: "attachmentBlock"
        widget: "object"
        required: false
        fields:
          - {label: "Пояснительный текст", name: "explanatoryText", widget: "string", required: false, default: "На данную вакансию требуется выполнить тестовое задание"}
          - {label: 'Имя файла', name: 'fileName', widget: 'string', required: false,  default: "Тестовое задание"}
          - {label: 'Файл', name: 'file', widget: 'file', required: false,  default: ""}
      - label: 'Текстовый блок "Что предлагаем взамен"'
        name: "sentence"
        widget: "object"
        fields:
          - label: "Название блока"
            name: "sentenceTitle"
            widget: "string"
            default: "Что предлагаем взамен"
          - label: 'Перечень требований'
            name: 'sentenceBody'
            widget: 'markdown'
            default: "<ul>
                        <li>
                          <img src=\"/img/doc.svg\" />
                          Официальное оформление по ТК РФ;
                        </li>
                        <li>
                          <img src=\"/img/cup.svg\" />
                          Удобный и светлый офис рядом с метро Цветной бульвар; кофе, чай и прочие вкусности;
                        </li>
                        <li>
                          <img src=\"/img/smile.svg\" />
                          Дружную, профессиональную команду единомышленников. Грамотные старшие товарищи
                          помогут, подтянут, научат. В нашей команде - разработчики front-end и back-end, есть
                          аналитик, дизайнер, специалист по UX, верстальщик, специалисты по внедрению и
                          тестированию, руководитель проекта;
                        </li>
                        <li>
                          <img src=\"/img/clock.svg\" />У нас нет жесткого графика. Каждый выбирает сам, в каком
                          режиме ему работать: кто-то приходит в офис к 8 утра, кто-то — к 11. Мы не заставляем
                          сотрудников работать сверх нормы. Главное — выполнять задачи в срок и не подводить
                          команду.
                        </li>
                        <li>
                          <img src=\"/img/keyboard.svg\" />
                          Все условия для разработки: у вас будут четко сформулированные задачи, требования на
                          ближайший спринт и план разработки определены на несколько месяцев вперед, готовая
                          верстка и дизайн;
                        </li>
                        <li>
                          <img src=\"/img/pc.svg\" />
                          Мы ведем задачи в Jira, описываем требования в CF, создаем макеты для верстки в
                          Zeplin, обсуждаем проекты в Slack;
                        </li>
                        <li>
                          <img src=\"/img/people.svg\" />
                          Возможность поработать как в продуктовой, так и в проектной команде;
                        </li>
                        <li>
                          <img src=\"/img/medal.svg\" />
                          Участие в крупных мегаинтересных проектах в разных отраслях, в т.ч. федерального
                          уровня. Один из последних проектов компании - уникальный публичный сервис-помощник
                          предпринимателям \"Бизнес-навигатор МСП\". Он предназначен для поиска наилучшего
                          местоположения для открытия бизнеса.
                        </li>
                        <li>
                          <img src=\"/img/lump.svg\" />
                          Возможности для саморазвития. Мы всегда за новые идеи и новые технологии.
                        </li>
                      </ul>"
      - label: "Последний блок"
        name: "footerText"
        widget: "markdown"
        default: "Хотите у нас работать? <br /> Пишите в чат или по указанным в вакансии контактам!"

